package com.yalex.codegen;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.yalex.automata.dfa.DFA;
import com.yalex.automata.dfa.DirectDfaBuilder;
import com.yalex.automata.minimization.DFAMinimizer;
import com.yalex.automata.syntax.SyntaxTree;
import com.yalex.automata.syntax.SyntaxTreeBuilder;
import com.yalex.model.LetDefinition;
import com.yalex.model.Rule;
import com.yalex.model.RuleSet;
import com.yalex.regex.RegexParser;
import com.yalex.regex.node.RegexNode;
import com.yalex.yal.YalFile;

/**
 * Genera un analizador léxico en Python a partir de un {@link YalFile} parseado.
 */
public final class PythonCodeGen {

    private PythonCodeGen() {
    }

    public static void generate(YalFile yal, Path outputPath) throws IOException {
        Objects.requireNonNull(yal, "yal");
        Objects.requireNonNull(outputPath, "outputPath");
        String py = generateString(yal);
        Files.writeString(outputPath, py, StandardCharsets.UTF_8);
    }

    public static String generateString(YalFile yal) {
        Objects.requireNonNull(yal, "yal");
        List<LetDefinition> lets = yal.getLetDefinitions();
        if (yal.getRuleSets().isEmpty()) {
            throw new IllegalArgumentException("el .yal no contiene ningún bloque rule");
        }
        RuleSet rs = yal.getRuleSets().get(0);
        List<Rule> rules = rs.getRules();

        List<DfaPayload> payloads = new ArrayList<>();
        List<Boolean> eofFlags = new ArrayList<>();
        List<String> actions = new ArrayList<>();

        for (Rule rule : rules) {
            String raw = rule.getPattern().trim();
            String expanded = LetExpander.apply(raw, lets);
            actions.add(rule.getAction());

            if (isEofPattern(expanded)) {
                payloads.add(null);
                eofFlags.add(true);
                continue;
            }
            eofFlags.add(false);
            RegexNode ast = RegexParser.parse(expanded);
            SyntaxTree tree = SyntaxTreeBuilder.build(ast);
            DFA dfa = DFAMinimizer.minimize(DirectDfaBuilder.build(tree));
            payloads.add(DfaPayload.from(dfa));
        }

        StringBuilder sb = new StringBuilder();
        String userHeader = yal.getHeader().trim();
        if (!userHeader.isEmpty()) {
            sb.append(userHeader).append("\n\n");
        }
        sb.append("# --- Generated by YALex ---\n\n");

        sb.append("class LexError(Exception):\n    pass\n\n");

        sb.append("_RULE_NAME = ").append(pyString(rs.getName())).append("\n\n");

        emitRuleData(sb, payloads, eofFlags);

        sb.append("\n");
        emitActions(sb, actions);

        sb.append("\n");
        emitMatcher(sb);

        sb.append("\n");
        String userFooter = yal.getTrailer().trim();
        if (!userFooter.isEmpty()) {
            sb.append("\n").append(userFooter).append("\n");
        }
        String tplFooter = loadTemplate("/templates/lexer_footer.py.template").trim();
        if (!tplFooter.isEmpty()) {
            sb.append("\n").append(tplFooter).append("\n");
        }

        return sb.toString();
    }

    private static boolean isEofPattern(String expandedPattern) {
        return expandedPattern.trim().equalsIgnoreCase("eof");
    }

    private static void emitRuleData(StringBuilder sb, List<DfaPayload> payloads, List<Boolean> eofFlags) {
        sb.append("_RULE_DFAS = [\n");
        for (int i = 0; i < payloads.size(); i++) {
            DfaPayload p = payloads.get(i);
            if (p == null) {
                sb.append("    None,  # rule ").append(i).append(" (eof)\n");
            } else {
                sb.append("    ");
                p.appendPython(sb);
                sb.append(",\n");
            }
        }
        sb.append("]\n\n");

        sb.append("_EOF_RULE = ");
        int eofIdx = -1;
        for (int i = 0; i < eofFlags.size(); i++) {
            if (eofFlags.get(i)) {
                eofIdx = i;
                break;
            }
        }
        sb.append(eofIdx).append("\n");
    }

    private static void emitActions(StringBuilder sb, List<String> actions) {
        for (int i = 0; i < actions.size(); i++) {
            sb.append("def _action_").append(i).append("(lexbuf, lxm):\n");
            indentAppend(sb, actions.get(i), 4);
            sb.append("\n\n");
        }
    }

    private static void indentAppend(StringBuilder sb, String code, int spaces) {
        String pad = " ".repeat(spaces);
        String[] lines = code.replace("\r\n", "\n").split("\n", -1);
        for (String line : lines) {
            sb.append(pad).append(line).append('\n');
        }
    }

    private static void emitMatcher(StringBuilder sb) {
        sb.append(
                "def _longest_match(dfa, buf, pos):\n"
                + "    if dfa is None:\n"
                + "        return None\n"
                + "    state = dfa['initial']\n"
                + "    trans = dfa['trans']\n"
                + "    acc = dfa['accept']\n"
                + "    last = None\n"
                + "    if acc[state]:\n"
                + "        last = pos - 1\n"
                + "    j = pos\n"
                + "    while j < len(buf):\n"
                + "        o = ord(buf[j])\n"
                + "        row = trans[state]\n"
                + "        ns = row.get(o)\n"
                + "        if ns is None:\n"
                + "            break\n"
                + "        state = ns\n"
                + "        if acc[state]:\n"
                + "            last = j\n"
                + "        j += 1\n"
                + "    return last\n\n"
                + "def next_token(buf, pos):\n"
                + "    if pos > len(buf):\n"
                + "        raise LexError('posición fuera del buffer')\n"
                + "    if pos == len(buf):\n"
                + "        if _EOF_RULE >= 0:\n"
                + "            lexbuf = ''\n"
                + "            lxm = lexbuf\n"
                + "            fn = globals()['_action_' + str(_EOF_RULE)]\n"
                + "            return fn(lexbuf, lxm), pos\n"
                + "        raise LexError('fin de entrada inesperado')\n"
                + "    best_end = None\n"
                + "    best_i = None\n"
                + "    best_score = None\n"
                + "    for i, dfa in enumerate(_RULE_DFAS):\n"
                + "        if dfa is None:\n"
                + "            continue\n"
                + "        end = _longest_match(dfa, buf, pos)\n"
                + "        if end is None:\n"
                + "            continue\n"
                + "        length = end - pos + 1\n"
                + "        if length == 0:\n"
                + "            continue\n"
                + "        score = (length, -i)\n"
                + "        if best_score is None or score > best_score:\n"
                + "            best_score = score\n"
                + "            best_end = end\n"
                + "            best_i = i\n"
                + "    if best_i is None:\n"
                + "        raise LexError('error léxico en posición ' + str(pos))\n"
                + "    lexbuf = buf[pos:best_end + 1]\n"
                + "    lxm = lexbuf\n"
                + "    fn = globals()['_action_' + str(best_i)]\n"
                + "    return fn(lexbuf, lxm), best_end + 1\n\n"
                + "def tokenize_all(buf):\n"
                + "    pos = 0\n"
                + "    out = []\n"
                + "    while pos < len(buf):\n"
                + "        tok, pos = next_token(buf, pos)\n"
                + "        out.append(tok)\n"
                + "    if _EOF_RULE >= 0:\n"
                + "        tok, _ = next_token(buf, pos)\n"
                + "        out.append(tok)\n"
                + "    return out\n");
    }

    private static String pyString(String s) {
        return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\"";
    }

    private static String loadTemplate(String classpath) {
        try (InputStream in = PythonCodeGen.class.getResourceAsStream(classpath)) {
            if (in == null) {
                return "";
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** Serialización del DFA para Python (transiciones por código ordinal). */
    private static final class DfaPayload {
        private final int initial;
        private final List<Boolean> accept;
        private final List<Map<Integer, Integer>> trans;

        private DfaPayload(int initial, List<Boolean> accept, List<Map<Integer, Integer>> trans) {
            this.initial = initial;
            this.accept = accept;
            this.trans = trans;
        }

        static DfaPayload from(DFA dfa) {
            int n = dfa.getStateCount();
            List<Boolean> acc = new ArrayList<>();
            List<Map<Integer, Integer>> rows = new ArrayList<>();
            for (int i = 0; i < n; i++) {
                acc.add(dfa.getState(i).isAccepting());
                rows.add(new java.util.TreeMap<>());
            }
            for (var e : dfa.getTransitionTable().entrySet()) {
                int from = e.getKey();
                for (var te : e.getValue().entrySet()) {
                    rows.get(from).put((int) te.getKey(), te.getValue());
                }
            }
            return new DfaPayload(dfa.getInitialStateId(), acc, rows);
        }

        void appendPython(StringBuilder sb) {
            sb.append("{ 'initial': ").append(initial).append(", ");
            sb.append("'accept': [");
            for (int i = 0; i < accept.size(); i++) {
                if (i > 0) {
                    sb.append(", ");
                }
                sb.append(accept.get(i) ? "True" : "False");
            }
            sb.append("], 'trans': [");
            for (int i = 0; i < trans.size(); i++) {
                if (i > 0) {
                    sb.append(", ");
                }
                sb.append("{");
                boolean first = true;
                for (var e : trans.get(i).entrySet()) {
                    if (!first) {
                        sb.append(", ");
                    }
                    first = false;
                    sb.append(e.getKey()).append(": ").append(e.getValue());
                }
                sb.append("}");
            }
            sb.append("] }");
        }
    }
}
