from tokens import PLUS, NUM

# --- Generated by YALex ---

class LexError(Exception):
    pass

_RULE_NAME = "gettoken"

_RULE_DFAS = [
    { 'initial': 1, 'accept': [True, False], 'trans': [{}, {9: 0, 10: 0, 32: 0}] },
    { 'initial': 1, 'accept': [True, False], 'trans': [{}, {48: 0, 49: 0, 50: 0, 51: 0, 52: 0, 53: 0, 54: 0, 55: 0, 56: 0, 57: 0}] },
    { 'initial': 1, 'accept': [True, False], 'trans': [{}, {43: 0}] },
    None,  # rule 3 (eof)
]

_EOF_RULE = 3

def _action_0(lexbuf, lxm):
    return lexbuf


def _action_1(lexbuf, lxm):
    return NUM


def _action_2(lexbuf, lxm):
    return PLUS


def _action_3(lexbuf, lxm):
    raise Exception('fin')



def _longest_match(dfa, buf, pos):
    if dfa is None:
        return None
    state = dfa['initial']
    trans = dfa['trans']
    acc = dfa['accept']
    last = None
    if acc[state]:
        last = pos - 1
    j = pos
    while j < len(buf):
        o = ord(buf[j])
        row = trans[state]
        ns = row.get(o)
        if ns is None:
            break
        state = ns
        if acc[state]:
            last = j
        j += 1
    return last

def next_token(buf, pos):
    if pos > len(buf):
        raise LexError('posición fuera del buffer')
    if pos == len(buf):
        if _EOF_RULE >= 0:
            lexbuf = ''
            lxm = lexbuf
            fn = globals()['_action_' + str(_EOF_RULE)]
            return fn(lexbuf, lxm), pos
        raise LexError('fin de entrada inesperado')
    best_end = None
    best_i = None
    best_score = None
    for i, dfa in enumerate(_RULE_DFAS):
        if dfa is None:
            continue
        end = _longest_match(dfa, buf, pos)
        if end is None:
            continue
        length = end - pos + 1
        if length == 0:
            continue
        score = (length, -i)
        if best_score is None or score > best_score:
            best_score = score
            best_end = end
            best_i = i
    if best_i is None:
        raise LexError('error léxico en posición ' + str(pos))
    lexbuf = buf[pos:best_end + 1]
    lxm = lexbuf
    fn = globals()['_action_' + str(best_i)]
    return fn(lexbuf, lxm), best_end + 1

def tokenize_all(buf):
    pos = 0
    out = []
    while pos < len(buf):
        tok, pos = next_token(buf, pos)
        out.append(tok)
    if _EOF_RULE >= 0:
        tok, _ = next_token(buf, pos)
        out.append(tok)
    return out


def helper():
    return 1

# YALex generated lexer footer template
