from tokens import ID, NUM, PLUS, MINUS, TIMES, DIV

# --- Generated by YALex ---

class LexError(Exception):
    pass

_RULE_NAME = "gettoken"

_RULE_DFAS = [
    { 'initial': 1, 'accept': [True, False], 'trans': [{}, {9: 0, 10: 0, 32: 0}] },
    { 'initial': 1, 'accept': [True, False], 'trans': [{32: 0, 48: 0, 49: 0, 50: 0, 51: 0, 52: 0, 53: 0, 54: 0, 55: 0, 56: 0, 57: 0, 65: 0, 66: 0, 67: 0, 68: 0, 69: 0, 70: 0, 71: 0, 72: 0, 73: 0, 74: 0, 75: 0, 76: 0, 77: 0, 78: 0, 79: 0, 80: 0, 81: 0, 82: 0, 83: 0, 84: 0, 85: 0, 86: 0, 87: 0, 88: 0, 89: 0, 90: 0, 97: 0, 98: 0, 99: 0, 100: 0, 101: 0, 102: 0, 103: 0, 104: 0, 105: 0, 106: 0, 107: 0, 108: 0, 109: 0, 110: 0, 111: 0, 112: 0, 113: 0, 114: 0, 115: 0, 116: 0, 117: 0, 118: 0, 119: 0, 120: 0, 121: 0, 122: 0}, {32: 0, 65: 0, 66: 0, 67: 0, 68: 0, 69: 0, 70: 0, 71: 0, 72: 0, 73: 0, 74: 0, 75: 0, 76: 0, 77: 0, 78: 0, 79: 0, 80: 0, 81: 0, 82: 0, 83: 0, 84: 0, 85: 0, 86: 0, 87: 0, 88: 0, 89: 0, 90: 0, 97: 0, 98: 0, 99: 0, 100: 0, 101: 0, 102: 0, 103: 0, 104: 0, 105: 0, 106: 0, 107: 0, 108: 0, 109: 0, 110: 0, 111: 0, 112: 0, 113: 0, 114: 0, 115: 0, 116: 0, 117: 0, 118: 0, 119: 0, 120: 0, 121: 0, 122: 0}] },
    { 'initial': 1, 'accept': [True, False], 'trans': [{}, {48: 0, 49: 0, 50: 0, 51: 0, 52: 0, 53: 0, 54: 0, 55: 0, 56: 0, 57: 0}] },
    { 'initial': 1, 'accept': [True, False], 'trans': [{}, {43: 0}] },
    { 'initial': 1, 'accept': [True, False], 'trans': [{}, {45: 0}] },
    { 'initial': 1, 'accept': [True, False], 'trans': [{}, {42: 0}] },
    { 'initial': 1, 'accept': [True, False], 'trans': [{}, {47: 0}] },
    { 'initial': 1, 'accept': [True, False], 'trans': [{}, {33: 0, 34: 0, 35: 0, 36: 0, 37: 0, 38: 0, 39: 0, 40: 0, 41: 0, 42: 0, 43: 0, 44: 0, 45: 0, 46: 0, 47: 0, 58: 0, 59: 0, 60: 0, 61: 0, 62: 0, 63: 0, 64: 0, 65: 0, 66: 0, 67: 0, 68: 0, 69: 0, 70: 0, 71: 0, 72: 0, 73: 0, 74: 0, 75: 0, 76: 0, 77: 0, 78: 0, 79: 0, 80: 0, 81: 0, 82: 0, 83: 0, 84: 0, 85: 0, 86: 0, 87: 0, 88: 0, 89: 0, 90: 0, 91: 0, 92: 0, 93: 0, 94: 0, 95: 0, 96: 0, 123: 0, 124: 0, 125: 0, 126: 0}] },
    None,  # rule 8 (eof)
]

_EOF_RULE = 8

def _action_0(lexbuf, lxm):
    return lexbuf


def _action_1(lexbuf, lxm):
    return ID


def _action_2(lexbuf, lxm):
    return NUM


def _action_3(lexbuf, lxm):
    return PLUS


def _action_4(lexbuf, lxm):
    return MINUS


def _action_5(lexbuf, lxm):
    return TIMES


def _action_6(lexbuf, lxm):
    return DIV


def _action_7(lexbuf, lxm):
    return UNKNOWN


def _action_8(lexbuf, lxm):
    raise Exception('EOF')



def _longest_match(dfa, buf, pos):
    if dfa is None:
        return None
    state = dfa['initial']
    trans = dfa['trans']
    acc = dfa['accept']
    last = None
    if acc[state]:
        last = pos - 1
    j = pos
    while j < len(buf):
        o = ord(buf[j])
        row = trans[state]
        ns = row.get(o)
        if ns is None:
            break
        state = ns
        if acc[state]:
            last = j
        j += 1
    return last

def next_token(buf, pos):
    if pos > len(buf):
        raise LexError('posición fuera del buffer')
    if pos == len(buf):
        if _EOF_RULE >= 0:
            lexbuf = ''
            lxm = lexbuf
            fn = globals()['_action_' + str(_EOF_RULE)]
            return fn(lexbuf, lxm), pos
        raise LexError('fin de entrada inesperado')
    best_end = None
    best_i = None
    best_score = None
    for i, dfa in enumerate(_RULE_DFAS):
        if dfa is None:
            continue
        end = _longest_match(dfa, buf, pos)
        if end is None:
            continue
        length = end - pos + 1
        if length == 0:
            continue
        score = (length, -i)
        if best_score is None or score > best_score:
            best_score = score
            best_end = end
            best_i = i
    if best_i is None:
        raise LexError('error léxico en posición ' + str(pos))
    lexbuf = buf[pos:best_end + 1]
    lxm = lexbuf
    fn = globals()['_action_' + str(best_i)]
    return fn(lexbuf, lxm), best_end + 1

def tokenize_all(buf):
    pos = 0
    out = []
    while pos < len(buf):
        tok, pos = next_token(buf, pos)
        out.append(tok)
    if _EOF_RULE >= 0:
        tok, _ = next_token(buf, pos)
        out.append(tok)
    return out


def post():
    return None

# YALex generated lexer footer template
